### ISSUE TITLE
how to save and load vocabulary?

### ISSUE THREAD

**Issue by suimo** [emiliofidalgo/ibow-lcd#2]
hi,I have tried the code with my own dataset and it works so nice ! now I want to save the vocabulary to a file and load from this file next time,how to fulfill this function?could you give me some advise?
thanks so much for any reply!

**Comment by emiliofidalgo** [comment]
Hi @suimo, very glad to see that you find the code useful. Currently, it is not possible to save and load vocabularies, since the idea is to build the dictionary online, while the camera / robot is navigating. Saving and loading vocabularies makes more sense in static approaches. Anyway, if you want to implement this funcionality, an idea could be to write on disk the variables stored on binary_index.h (see obindex2). As previously said, ibow-lcd was not developed with this idea in mind.

**Comment by suimo** [comment]
@emiliofidalgo thanks a lot for your reply,I will try as you advised !

**Comment by Taeyoung96** [comment]
@suimo   
Hi, did you make functions that save and load the vocabulary?  
When you are did it, could I get your code or some tips?  

Thanks,
