### ISSUE TITLE
evaluation data

### ISSUE THREAD

**Issue by yvaine** [emiliofidalgo/ibow-lcd#5]
Thanks for you job!  If I want to run evaluation code, it can't find base directory data such as groundtruth.mat and imageCoords.mat, where can i get them?

**Comment by emiliofidalgo** [comment]
Hi @Yvaine, thank you for testing the code. These files are not included in the repository. I can provide you the files for the datasets we used in the paper, but if you want to use your own sequence, you have to generate your own ones following the corresponding format. I would say that the ground truth files are the same that the ones stored here:

https://github.com/emiliofidalgo/htmap/tree/master/matlab/gtruths

The coordinate files were obtained from the GPS positions of each dataset, but adapted to be used with our postprocessing Matlab files. I can share these files with you privately if you send me an email address.

**Comment by yvaine** [comment]
Thank you for your reply very much.  As you mentioned, if i have myself data, how can i get groundtruth.mat? Through match every descriptor in each image and choose the best score, but how to  set the threshold if have not only one candidate.

**Comment by emiliofidalgo** [comment]
So if you need to generate your own ground truth, you can see one of the examples I told you above. Open Matlab, and load, for instance, groundtruth_CC.mat (City Centre). After that, you can see that it includes a square matrix with the number of images as rows and columns. Then, you have to put a '1' when image in colum _j_ closes a loop with image in row _i_ by your own observation. Since normally some images can close a loop with anoter one, you can put a set of consecutive '1' to give some tolerance to your algorithm.

**Comment by yvaine** [comment]
yes, i know how to do it. Thank you for your reply.

**Comment by emiliofidalgo** [comment]
You're welcome!

**Comment by Adamqu199541** [comment]
Hi, thanks for sharing your work about "ibow".  I now want to use the evaluation code in ibow to evaluate my algorithm. Could you please send me the "imageCoords. mat" for each sequence. I have found 'groundtruth. mat'.  
My email number is 904804734@qq.com
